### ISSUE TITLE
 Product variation images are not importing with variants #57 

### ISSUE THREAD

**Issue by musawirjon** [bagisto/laravel-aliexpress-dropship-chrome-extension#10]
Hello,
I am importing products from aliexpress, Products are importing perfectly but all the variants like description and images are missing due to this on front end changing variants images and other details are not showing for the product variant accept prices that are changing with variation changes.

screenshot #1: wthout choosing variants
https://prnt.sc/yhpn5a

screenshot #2 Price changed but other details like image in the slider and variant description are not updating
https://prnt.sc/yhpsnt

Please have a look into it.

**Comment by prateek-webkul** [comment]
Please refer the link below having same issue
https://github.com/bagisto/laravel-aliexpress-dropship/issues/57
