### ISSUE TITLE
extension not work 

### ISSUE THREAD

**Issue by ibrahimMH13** [bagisto/laravel-aliexpress-dropship-chrome-extension#5]
![error](https://user-images.githubusercontent.com/9980742/95297762-aceec800-0883-11eb-827b-6e49bf2c3783.PNG)
at moment the extension not work normally ,
 it connect to the store without anything else no popup not detect aliexpress website

**Comment by ibrahimMH13** [comment]
there error in network tab
Request URL: https://fourier.taobao.com/ts?url=https%3A%2F%2Flaradeux.xxxxxxx.com%2Fdropship%2Faliexpress%2Forders%3Fcallback%3DjQuery32106689862685324741_1602053994835%26_%3D1602053994836&token=BIGB_miPuq3oudaZNr6KmWpPkM2brvWgwPcoiePWXgjmyqGcK_5-cJTMrCaMbo3Y&cna=OVMEGIjn2CoCAVVyb6h%2FM46y&ext=0
Referrer Policy: strict-origin-when-cross-origin
:authority: fourier.taobao.com
:method: GET
:path: /ts?url=https%3A%2F%2Flaradeux.xxxxxxx.com%2Fdropship%2Faliexpress%2Forders%3Fcallback%3DjQuery32106689862685324741_1602053994835%26_%3D1602053994836&token=BIGB_miPuq3oudaZNr6KmWpPkM2brvWgwPcoiePWXgjmyqGcK_5-cJTMrCaMbo3Y&cna=OVMEGIjn2CoCAVVyb6h%2FM46y&ext=0
:scheme: https
accept: image/avif,image/webp,image/apng,image/*,*/*;q=0.8
accept-encoding: gzip, deflate, br
accept-language: ar,en-US;q=0.9,en;q=0.8
referer: https://www.aliexpress.com/
sec-fetch-dest: image
sec-fetch-mode: no-cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4278.0 Safari/537.36
url: https://laradeux.xxxxxxx.com/dropship/aliexpress/orders?callback=jQuery32106689862685324741_1602053994835&_=1602053994836
token: BIGB_miPuq3oudaZNr6KmWpPkM2brvWgwPcoiePWXgjmyqGcK_5-cJTMrCaMbo3Y
cna: OVMEGIjn2CoCAVVyb6h/M46y
ext: 0

**Comment by prateek-webkul** [comment]
Hello @ibrhaim13 ,

Please specify aliexpress extension version you are using..

**Comment by ibrahimMH13** [comment]
@prateek-webkul v0.1.0

**Comment by prateek-webkul** [comment]
@ibrhaim13 , please update it and download the latest version from https://github.com/bagisto/laravel-aliexpress-dropship-chrome-extension (master branch).

Thanks

**Comment by ibrahimMH13** [comment]
HI @prateek-webkul ,
-- the extension work but there some bugs
1- always price when fetch product from aliExpress to model is 0, when change manual still 
send it to store a zero,
2-  when import a product show error message say product already imported somehow that when store is empty
finally thanks you to match for help

**Comment by prateek-webkul** [comment]
@ibrhaim13 ,
You are using our old version. Download latest version from https://github.com/bagisto/laravel-aliexpress-dropship/tree/v1.1.2

**Comment by prateek-webkul** [comment]
Hi @ibrhaim13, 

This issue has been opened for more than a month. And, it seems that your issue is resolved. Therefore, I am closing the issue.

Thanks
