### ISSUE TITLE
Can't import products or even can't re change store url validation. 

### ISSUE THREAD

**Issue by musawirjon** [bagisto/laravel-aliexpress-dropship-chrome-extension#9]
Hello,
I tried your extension isn't working while I import products it says can't import can't import on all products. and even I can't add new url validation details. what I do please guide me

**Comment by prateek-webkul** [comment]
Hello @musawirjon ,

Please get the latest version from https://github.com/bagisto/laravel-aliexpress-dropship/tree/master and from the readme guide for installation. And still, you have some issues please attach the aliexpress product link.

**Comment by musawirjon** [comment]
Hello @prateek-webkul  product variation images still not working. As it working in normal product uploading not work with imported products from aliexpress.
This is needed to changes image in the slider while user select any variant. Please guide me so I can make those changes and variation color change should change the image in slider. thank you

**Comment by prateek-webkul** [comment]
@musawirjon Fixed. Please take a latest pull from https://github.com/bagisto/laravel-aliexpress-dropship/tree/master.

Thanks
